//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Usuario/IdeaProjects/Gramarr/MiniCParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MiniCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMiniCParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MiniCParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] MiniCParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] MiniCParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMember([NotNull] MiniCParser.ClassMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] MiniCParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDecl([NotNull] MiniCParser.MethodDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] MiniCParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] MiniCParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] MiniCParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] MiniCParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MiniCParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStmt([NotNull] MiniCParser.ExprStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] MiniCParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] MiniCParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] MiniCParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] MiniCParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.breakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStmt([NotNull] MiniCParser.BreakStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.readStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadStmt([NotNull] MiniCParser.ReadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWriteStmt([NotNull] MiniCParser.WriteStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] MiniCParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.assignExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpr([NotNull] MiniCParser.AssignExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] MiniCParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] MiniCParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.eqExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpr([NotNull] MiniCParser.EqExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelExpr([NotNull] MiniCParser.RelExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] MiniCParser.AddExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulExpr([NotNull] MiniCParser.MulExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] MiniCParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] MiniCParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.location"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocation([NotNull] MiniCParser.LocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] MiniCParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] MiniCParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] MiniCParser.LiteralContext context);
}
